### ISSUE TITLE
Default submenus will no longer show

### ISSUE THREAD

**Issue by ghost** [Funkd/ScopeNox#1]
Hi Funkd. I'm not sure if you're still active with this skin, but if so could you please pull the latest contents of Nox 5's shortcuts folder into your skin.

The new version of the skin shortcuts script on the repo has dropped legacy support for the .shortcuts files used by your skin for the default submenu's, so they will no longer show for users on Isengard or later.

Cheers.

**Comment by ChrisDev83** [comment]
Thanks for the heads up Ignoble, I'll get that done soon. I've been very busy with other things this last while and haven't had time to keep on top of changes!

**Comment by ChrisDev83** [comment]
This should now be fixed. I have updated the shortcuts folder and tested in Isengard. Could you check it and let me know?

Thanks.

**Comment by ghost** [comment]
All looks good :)

**Comment by ChrisDev83** [comment]
Cheers!
