### ISSUE TITLE
Only 2:40:1

### ISSUE THREAD

**Issue by arch845** [Funkd/ScopeNox#2]
Hi, Kevin here, first time posting, is there a way just to constantly have only 2:40:1? For example, when watching music videos I have to keep changing to 2:40:1 for each music video. Thank you very much for your efforts.

**Comment by ChrisDev83** [comment]
Hi, It should stay as 2.40. What steps do you do to reproduce this?

Chris

**Comment by arch845** [comment]
Hi, when I'm using UK music video jukebox, and each time I select a new
video I have to reapply scope.

**Comment by ChrisDev83** [comment]
Ok will install that add-on and see. If its something within the addon it
might be an issue, but if not I should be able to sort it.

**Comment by arch845** [comment]
Thank you. You're a star!

**Comment by ChrisDev83** [comment]
One more question, I'm guessing you mean the ScopeMask option? And not the
toggle between 2.35 and 2.40?

**Comment by arch845** [comment]
Hi, I'm using Scope Nox 1.8-5.6.0
On 6 Jun 2016 18:03, "Funkd" notifications@github.com wrote:

Ok will install that add-on and see. If its something within the addon it
might be an issue, but if not I should be able to sort it.

On 6 June 2016 at 18:01, arch845 notifications@github.com wrote:

> Hi, when I'm using UK music video jukebox, and each time I select a new
> video I have to reapply scope.
> On 6 Jun 2016 17:57, "Funkd" notifications@github.com wrote:
> 
> > Hi, It should stay as 2.40. What steps do you do to reproduce this?
> > 
> > Chris
> > 
> > On 4 June 2016 at 12:22, arch845 notifications@github.com wrote:
> > 
> > > Hi, Kevin here, first time posting, is there a way just to constantly
> > > have
> > > only 2:40:1? For example, when watching music videos I have to keep
> > > changing to 2:40:1 for each music video. Thank you very much for your
> > > efforts.
> > > 
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub
> > > https://github.com/Funkd/ScopeNox/issues/2, or mute the thread
> > > <
> 
> https://github.com/notifications/unsubscribe/AMJ2y633jCEhWxyQ7r1xqowohVeIlIRKks5qIWAFgaJpZM4IuHBN
> 
> > > .
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/Funkd/ScopeNox/issues/2#issuecomment-224019623, or
> > mute
> > the thread
> > <
> 
> https://github.com/notifications/unsubscribe/ASIpXTusWDo0q4lCFMdRzjC-xBKZRON6ks5qJFFrgaJpZM4IuHBN
> 
> > .
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly, view it on GitHub
> https://github.com/Funkd/ScopeNox/issues/2#issuecomment-224020883, or
> mute
> the thread
> <
> https://github.com/notifications/unsubscribe/AMJ2ywX5Ij0NcHbMenqCZKa3sd6p0Z7Bks5qJFJ1gaJpZM4IuHBN
> 
> .

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/Funkd/ScopeNox/issues/2#issuecomment-224021402, or mute
the thread
https://github.com/notifications/unsubscribe/ASIpXdjuypppkG_hwptQTWK3ULF3ixbwks5qJFLdgaJpZM4IuHBN
.

**Comment by ChrisDev83** [comment]
Ok, if you want to test this out now without download a full zip. Download
the following files from Github. A replace the existing files in your Kodi
skin folder :

language/English/strings.po
/scopeformat/SkinSettings.xml
/scopeformat/variables.xml
/scopeformat/VideoFullScreen.xml

What you want to do then is, go to the Skin Settings screen and set the
'Remember Scope Mask' option to Yes. That should then keep it to what you
had last set.

Let me know how you get on.

Chris.

**Comment by arch845** [comment]
Thanks, I did not notice the "Remember Scope Mask" option in the skin
settings. I will try your surjestions tomorrow. Do I use an xlm editor to
change the script. Not to technically minded.

**Comment by ChrisDev83** [comment]
No I just added the 'Remember Scope Mask' option there now :). I'll be
uploading a new release file shortly. I'll mail you the link once its done.

Chris.

**Comment by arch845** [comment]
Thanks. I will send you another donation then. Thank you.

**Comment by ChrisDev83** [comment]
No not at all man. Don't worry about it. I got the previous one, thats
enough :) Thanks for that!

Chris.

**Comment by ChrisDev83** [comment]
New release file :

https://github.com/Funkd/ScopeNox/releases/download/1.9/skin.scope.nox.1.9.zip

You might need to uninstall the ScopeNox skin you have first.

Chris.

**Comment by arch845** [comment]
Sorry for bothering you again Chris,  I forgot how to install it. I deleted
the old version.

**Comment by arch845** [comment]
Got it installed. Thanks. Testing now.

**Comment by arch845** [comment]
Works like a charm!  Another question, what res is the backdrop photo used.
So I can apply cinema curtains if I can find one? I think most people would
like one for their projector screens. Thanks.

**Comment by ChrisDev83** [comment]
Just saw your replies. Glad you got sorted :) Background images are usually
1920x1080, keep in mind that the top and bottom will be blacked out for the
scope view. You can replace the file
addons/skin.scope.nox.1.9/backgrounds/default.png with you new one and that
should work.

Chris.

**Comment by ChrisDev83** [comment]
Fixed in 1.9

**Comment by arch845** [comment]
hi again, are you still working on this? if so could you add the ability to
add bluray/4k covers for (movies only section). i have potplayer working as
an external player for by bdiso,s  (way better quality) that the default
player. would it be possible to make potplayer or mpc-hc  the default
player for internet streams aswell? keep up the good work!

kev. from ireland.

On 7 June 2016 at 10:04, Funkd notifications@github.com wrote:

> Fixed in 1.9
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Funkd/ScopeNox/issues/2#issuecomment-224222144, or mute
> the thread
> https://github.com/notifications/unsubscribe/ASIpXSJR1b_mDhM4TGz0J3nm0hVtTvkiks5qJTQUgaJpZM4IuHBN
> .

## 

Regards Kev.

**Comment by ChrisDev83** [comment]
Hey Kev,
     Havent done anything on this in a while but I can take a look at adding bluray covers. Regarding the external player, not sure how to go about that as its a Kodi setting rather than a skin setting. Check out http://kodi.wiki/view/external_players , it might point you in the right direction. If I think on anything else I'll let ya know.

Chris.

**Comment by arch845** [comment]
Thank you.

**Comment by arch845** [comment]
Something like these covers.

https://goo.gl/images/2GHntS

**Comment by arch845** [comment]
Hi, if you are ever doing another 21:9 version, would you consider this. It
would look great on a large projector screen as the text is small. Love
your work. Thanks

https://goo.gl/images/iMvAbr
